---

- name: add app user to www-data group
  user: name=app groups=www-data

- name: create WSGI script file
  template: src=etc/ckan/default/apache.wsgi.j2 dest="{{ ckan_config_directory }}/apache.wsgi"

- name: configure default apache virtual host
  template: src=etc/apache2/sites-available/default.j2 dest=/etc/apache2/sites-available/default # no validation currently
  notify:
    - Restart Apache
  when: ansible_distribution_version == "12.04"

- name: configure default apache virtual host
  template: src=etc/apache2/sites-available/default.j2 dest=/etc/apache2/sites-available/000-default.conf # no validation currently
  notify:
    - Restart Apache
  when: ansible_distribution_version == "14.04"

- name: configure apache ports.conf
  template: src=etc/apache2/ports.conf.j2 dest=/etc/apache2/ports.conf # no validation currently
  when: ansible_distribution_version == "14.04"
