---
# tasks file for CKAN


# These tasks are required to create a viable CKAN instance (i.e. required)

- include: prepare_for_installation.yml

- include: install_ckan.yml

- include: configure_solr.yml

- include: configure_apache_wsgi.yml

- include: configure_nginx.yml

- include: configure_ckan.yml

- include: setup_ckan_db.yml

# These tasks are optional depending on the features selected (i.e. optional)

- include: create_ckan_super_user.yml

- include: populate_ckan_with_test_data.yml
